[package]
name = "AvrEmulator"
version = "0.1.0"
edition = "2021"

[dependencies]
bin_file = "0.1.1"
structopt = "0.3"
log = "0.4"
env_logger = "0.11"
serial_test = "3.2"
strum = "0.26"
strum_macros = "0.26"

[package.metadata.scripts]
coverage = "cargo tarpaulin --no-fail-fast --out html"