name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build docker images
      uses: docker/build-push-action@v6
      with:
        context: .devcontainer
        push: false #push: true  
        outputs: type=cacheonly
        tags: prorokwielki/avr_emulator:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        run: docker run -v $PWD:/srv -w/srv prorokwielki/avr_emulator cargo build
