name: Coverage

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.devcontainer/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.devcontainer/**'
  workflow_run:
    workflows: ["Docker build"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Push to coveralls.io
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: docker run --security-opt seccomp=unconfined -v $PWD:/srv -w/srv pawelwarzecha/avr_emulator:latest sh -c "git config --global --add safe.directory /srv && cargo tarpaulin --no-fail-fast --coveralls $COVERALLS_REPO_TOKEN"
