name: Docker build

on:
  push:
    branches: [ "master" ]
    paths:
        - '.devcontainer/Dockerfile'
  pull_request:
    branches: [ "master" ]
    paths:
        - '.devcontainer/Dockerfile'
        
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: pawelwarzecha
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build docker images
      uses: docker/build-push-action@v6
      with:
        context: .devcontainer
        tags: prorokwielki/avr_emulator:latest
        push: true
     
