name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Show me what you got
      run: ls -al ${{ github.workspace }}
    - name: Show me what you got 2
      run: ls -al
    - name: Build docker images
      uses: docker/build-push-action@v6
      with:
        context: .devcontainer
        push: false
        tags: local
    - name: Run tests
      run: docker run -it -v $PWD:/srv -w/srv local cargo test

