name: Test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.devcontainer/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.devcontainer/**'
  workflow_run:
    workflows: ["Docker build"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: build 
      run: docker run -v $PWD:/srv -w/srv pawelwarzecha/avr_emulator ~/.cargo/bin/cargo test
